spring.application.name=parcialdos
server.port=8080

# CONFIGURACIÓN DE BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Prueba123456.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver # Agrega o verifica esta línea

# CONFIGURACIÓN DE JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=update # Te recomiendo cambiarlo temporalmente a 'update' para que se conecte
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Inicialización de la base de datos con scripts
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
